# Generated by Django 4.1.2 on 2022-12-04 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_edit_date_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 12, 0, 46, 836459)),
        ),
    ]
