# Generated by Django 4.1.2 on 2022-12-04 12:46

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_title_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='media/blank.png', upload_to=core.models.Account.media_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 13, 46, 43, 827003)),
        ),
    ]
